"""NOVA Heartbeat — Constants & Types"""

import math
from enum import Enum

PHI = 1.6180339887498948482
PHI_INV = 0.6180339887498948482
AMOR = 0.3819660112501051518
PHI_SQUARED = PHI * PHI
PHI_CUBED = PHI_SQUARED * PHI
PHI_FOURTH = PHI_CUBED * PHI
SCHUMANN_FREQUENCY = 7.83
SCHUMANN_PERIOD_MS = 1000.0 / SCHUMANN_FREQUENCY
HEARTBEAT_MS = 873  # φ⁴ × Schumann period

class BeatType(str, Enum):
    SYSTOLE = "SYSTOLE"
    DIASTOLE = "DIASTOLE"
    SYNC = "SYNC"
    EMERGENCY = "EMERGENCY"

class RhythmState(str, Enum):
    NORMAL = "NORMAL"
    TACHYCARDIA = "TACHYCARDIA"
    BRADYCARDIA = "BRADYCARDIA"
    ARRHYTHMIA = "ARRHYTHMIA"
    ASYSTOLE = "ASYSTOLE"

class PhaseState(str, Enum):
    LOCKED = "LOCKED"
    DRIFTING = "DRIFTING"
    RESYNC = "RESYNC"
    FREE = "FREE"
