#!/usr/bin/env python3
"""Scale layer for NOVA polyglot coding capsules.

This module adds project/session orchestration, template generation, artifact
hash manifests, and deploy handoff packets without pretending public deployment
already exists.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import time
import uuid
from dataclasses import asdict, dataclass
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent
DEFAULT_WORKSPACE_ROOT = ROOT / "workspace"
DEFAULT_DEPLOY_ROOT = ROOT / "deployments"


@dataclass(frozen=True)
class CapsuleSession:
    session_id: str
    project: str
    workspace: str
    preview_url: str
    status: str
    created_at: float
    updated_at: float

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _sessions_path(workspace_root: pathlib.Path) -> pathlib.Path:
    return workspace_root / ".nova" / "sessions.json"


def _read_json(path: pathlib.Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: pathlib.Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def safe_name(name: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "-" for ch in name.strip())
    cleaned = "-".join(part for part in cleaned.split("-") if part)
    return cleaned or "nova-project"


def create_session(project: str = "nova-project", workspace_root: str | None = None) -> dict[str, Any]:
    root = pathlib.Path(workspace_root or DEFAULT_WORKSPACE_ROOT).resolve()
    root.mkdir(parents=True, exist_ok=True)
    project_name = safe_name(project)
    session_id = uuid.uuid4().hex
    workspace = root / "sessions" / session_id / project_name
    preview = workspace / "preview"
    preview.mkdir(parents=True, exist_ok=True)
    now = time.time()
    session = CapsuleSession(
        session_id=session_id,
        project=project_name,
        workspace=str(workspace),
        preview_url=f"/preview/{session_id}/index.html",
        status="active",
        created_at=now,
        updated_at=now,
    )
    sessions = _read_json(_sessions_path(root), [])
    sessions.append(session.to_dict())
    _write_json(_sessions_path(root), sessions)
    return session.to_dict()


def list_sessions(workspace_root: str | None = None) -> list[dict[str, Any]]:
    root = pathlib.Path(workspace_root or DEFAULT_WORKSPACE_ROOT).resolve()
    return _read_json(_sessions_path(root), [])


def project_template(kind: str = "web") -> dict[str, str]:
    if kind == "python":
        return {
            "hello.py": "print('hello from NOVA scaled capsule')\n",
            "README.md": "# NOVA Python Capsule\n\nGenerated by the NOVA polyglot coding capsule.\n",
        }
    if kind == "cpp":
        return {
            "main.cpp": "#include <iostream>\nint main(){ std::cout << \"hello from NOVA C++ capsule\\n\"; return 0; }\n",
            "README.md": "# NOVA C++ Capsule\n\nGenerated by the NOVA polyglot coding capsule.\n",
        }
    if kind == "java":
        return {
            "Main.java": "public class Main { public static void main(String[] args) { System.out.println(\"hello from NOVA Java capsule\"); } }\n",
            "README.md": "# NOVA Java Capsule\n\nGenerated by the NOVA polyglot coding capsule.\n",
        }
    return {
        "index.html": """<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>NOVA Scaled Capsule</title>
  <link rel=\"stylesheet\" href=\"styles.css\">
</head>
<body>
  <main class=\"shell\">
    <p class=\"eyebrow\">NOVA Polyglot Capsule</p>
    <h1>Live Coding Session</h1>
    <p>This frontend was generated inside a governed coding capsule with preview and deploy handoff lanes.</p>
  </main>
  <script src=\"app.js\"></script>
</body>
</html>
""",
        "styles.css": "body{margin:0;font-family:Inter,system-ui,sans-serif;background:#020617;color:#f8fafc}.shell{max-width:960px;margin:0 auto;padding:80px 32px}.eyebrow{color:#38bdf8;text-transform:uppercase;letter-spacing:.18em;font-weight:800}h1{font-size:72px;line-height:.9;margin:12px 0;background:linear-gradient(90deg,#fff,#93c5fd,#22c55e);-webkit-background-clip:text;color:transparent}p{font-size:22px;color:#cbd5e1;line-height:1.55}",
        "app.js": "console.log('NOVA scaled capsule preview live');\n",
        "README.md": "# NOVA Web Capsule\n\nGenerated by the NOVA polyglot coding capsule.\n",
    }


def init_project(workspace: str, kind: str = "web") -> dict[str, Any]:
    root = pathlib.Path(workspace).resolve()
    root.mkdir(parents=True, exist_ok=True)
    files = project_template(kind)
    written: list[str] = []
    for name, content in files.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(name)
    return {"ok": True, "workspace": str(root), "kind": kind, "files": written}


def hash_file(path: pathlib.Path, root: pathlib.Path) -> dict[str, Any]:
    data = path.read_bytes()
    return {
        "path": str(path.relative_to(root)),
        "bytes": len(data),
        "sha256": hashlib.sha256(data).hexdigest(),
    }


def build_hash_manifest(workspace: str, include_receipts: bool = True) -> dict[str, Any]:
    root = pathlib.Path(workspace).resolve()
    files: list[dict[str, Any]] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if not include_receipts and ".nova" in path.parts:
            continue
        files.append(hash_file(path, root))
    manifest = {
        "schema": "nova.polyglot.hash-manifest.v1",
        "workspace": str(root),
        "generated_at": time.time(),
        "file_count": len(files),
        "files": files,
    }
    out = root / ".nova" / "hash-manifest.json"
    _write_json(out, manifest)
    return manifest


def build_deploy_packet(workspace: str, target: str = "github-handoff") -> dict[str, Any]:
    root = pathlib.Path(workspace).resolve()
    manifest = build_hash_manifest(str(root))
    packet = {
        "schema": "nova.polyglot.deploy-packet.v1",
        "target": target,
        "workspace": str(root),
        "generated_at": time.time(),
        "status": "ready-for-handoff",
        "boundary": "local deploy packet only; no public external deployment claimed",
        "manifest_path": str(root / ".nova" / "hash-manifest.json"),
        "file_count": manifest["file_count"],
    }
    _write_json(root / ".nova" / "deploy-packet.json", packet)
    return packet
