// ============================================================================
// MEDINA TECH — CONFIDENTIAL & PROPRIETARY
// ============================================================================
// Component: VaultDashboard — Artifact Vault Visualization
// PARALLAX Drone Swarm Simulation — Medina Tech 2026
//
// The organism generates artifacts. This is where they live:
//   - Videos from world model simulations
//   - Audio from neural rhythms
//   - NFTs from dream states
//   - Game assets from simulacrum
//   - Simulations from preplay
// ============================================================================

import React, { useState, useMemo } from 'react';

const RARITY_COLORS = {
  common: '#888888',
  uncommon: '#00aa44',
  rare: '#0088ff',
  epic: '#aa44ff',
  legendary: '#ff8800',
  mythic: '#ff4488',
  divine: '#ffd700',
};

const TYPE_ICONS = {
  video: '🎬',
  audio: '🎵',
  voice: '🗣️',
  image: '🖼️',
  nft: '💎',
  gameAsset: '🎮',
  simulation: '🌐',
  model3D: '📐',
  code: '💻',
  document: '📄',
};

const SOURCE_LABELS = {
  OrganismDream: 'Dream',
  WorldModelSimulation: 'World Model',
  SharpWaveRipple: 'SWR Memory',
  HippocampalPreplay: 'Preplay',
  SimulacrumPrediction: 'Simulacrum',
  UserRequest: 'Requested',
  AutoGenerated: 'Auto',
};

// ─── ARTIFACT CARD ────────────────────────────────────────────────────────────
function ArtifactCard({ artifact, onSelect, selected }) {
  const rarityColor = RARITY_COLORS[artifact.rarity] || RARITY_COLORS.common;
  
  return (
    <div
      onClick={() => onSelect(artifact)}
      style={{
        background: selected ? '#1a2a4e' : '#0a1a2e',
        border: `1px solid ${selected ? rarityColor : '#1a3a5c'}`,
        borderRadius: 6,
        padding: 10,
        cursor: 'pointer',
        transition: 'all 0.2s',
        boxShadow: selected ? `0 0 12px ${rarityColor}44` : 'none',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span style={{ fontSize: 20 }}>{TYPE_ICONS[artifact.type] || '📦'}</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 10, color: '#adf', fontWeight: 'bold' }}>
            {artifact.name}
          </div>
          <div style={{ fontSize: 8, color: '#68a' }}>
            {artifact.type} • {SOURCE_LABELS[artifact.source] || artifact.source}
          </div>
        </div>
        <div style={{
          fontSize: 8,
          padding: '2px 6px',
          borderRadius: 8,
          background: `${rarityColor}22`,
          color: rarityColor,
          border: `1px solid ${rarityColor}`,
          textTransform: 'uppercase',
        }}>
          {artifact.rarity}
        </div>
      </div>
      
      <div style={{ fontSize: 8, color: '#68a', marginBottom: 4 }}>
        {artifact.description?.slice(0, 60) || 'No description'}
        {artifact.description?.length > 60 && '...'}
      </div>
      
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 8 }}>
        <span style={{ color: '#4af' }}>
          {formatSize(artifact.contentSize)}
        </span>
        <span style={{ color: artifact.nftData ? '#ffd700' : '#333' }}>
          {artifact.nftData ? '💎 NFT' : ''}
        </span>
        <span style={{ color: '#68a' }}>
          {formatAge(artifact.createdAt)}
        </span>
      </div>
    </div>
  );
}

// ─── ARTIFACT DETAIL ──────────────────────────────────────────────────────────
function ArtifactDetail({ artifact }) {
  if (!artifact) {
    return (
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        color: '#446',
        fontSize: 11,
      }}>
        Select an artifact to view details
      </div>
    );
  }
  
  const rarityColor = RARITY_COLORS[artifact.rarity] || RARITY_COLORS.common;
  
  return (
    <div style={{ padding: 12 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
        <span style={{ fontSize: 40 }}>{TYPE_ICONS[artifact.type] || '📦'}</span>
        <div>
          <div style={{ fontSize: 14, color: '#adf', fontWeight: 'bold' }}>
            {artifact.name}
          </div>
          <div style={{
            fontSize: 10,
            padding: '2px 8px',
            borderRadius: 10,
            background: `${rarityColor}22`,
            color: rarityColor,
            border: `1px solid ${rarityColor}`,
            display: 'inline-block',
            marginTop: 4,
          }}>
            {artifact.rarity?.toUpperCase()}
          </div>
        </div>
      </div>
      
      <div style={{ fontSize: 10, color: '#adf', marginBottom: 12 }}>
        {artifact.description || 'No description available'}
      </div>
      
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        <DetailField label="Type" value={artifact.type} />
        <DetailField label="Source" value={SOURCE_LABELS[artifact.source] || artifact.source} />
        <DetailField label="Size" value={formatSize(artifact.contentSize)} />
        <DetailField label="Created" value={formatDate(artifact.createdAt)} />
        <DetailField label="Views" value={artifact.viewCount || 0} />
        <DetailField label="Downloads" value={artifact.downloadCount || 0} />
      </div>
      
      {artifact.nftData && (
        <div style={{
          marginTop: 12,
          padding: 10,
          background: '#1a1a2e',
          border: '1px solid #ffd700',
          borderRadius: 6,
        }}>
          <div style={{ fontSize: 10, color: '#ffd700', marginBottom: 8 }}>
            💎 NFT DATA
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
            <DetailField label="Token ID" value={`#${artifact.nftData.tokenId}`} />
            <DetailField label="Collection" value={artifact.nftData.collectionId} />
            <DetailField label="Standard" value={artifact.nftData.standard} />
            <DetailField label="Royalty" value={`${artifact.nftData.royaltyPercent}%`} />
          </div>
        </div>
      )}
      
      {artifact.metadata && artifact.metadata.length > 0 && (
        <div style={{ marginTop: 12 }}>
          <div style={{ fontSize: 9, color: '#6af', marginBottom: 6 }}>METADATA</div>
          {artifact.metadata.map(([key, value], i) => (
            <div key={i} style={{ fontSize: 8, color: '#68a', marginBottom: 2 }}>
              <span style={{ color: '#4af' }}>{key}:</span> {value}
            </div>
          ))}
        </div>
      )}
      
      <div style={{ display: 'flex', gap: 8, marginTop: 16 }}>
        <ActionButton icon="👁️" label="View" />
        <ActionButton icon="⬇️" label="Download" />
        {!artifact.nftData && <ActionButton icon="💎" label="Mint NFT" highlight />}
      </div>
    </div>
  );
}

function DetailField({ label, value }) {
  return (
    <div>
      <div style={{ fontSize: 8, color: '#68a' }}>{label}</div>
      <div style={{ fontSize: 10, color: '#adf' }}>{value}</div>
    </div>
  );
}

function ActionButton({ icon, label, highlight }) {
  return (
    <button style={{
      flex: 1,
      padding: '6px 12px',
      background: highlight ? '#2a2a4e' : '#0a1a2e',
      border: `1px solid ${highlight ? '#ffd700' : '#1a3a5c'}`,
      borderRadius: 4,
      color: highlight ? '#ffd700' : '#4af',
      fontSize: 9,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    }}>
      {icon} {label}
    </button>
  );
}

// ─── VAULT STATS ──────────────────────────────────────────────────────────────
function VaultStats({ stats }) {
  return (
    <div style={{
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: 8,
      padding: '8px 12px',
      borderBottom: '1px solid #1a3a5c',
    }}>
      <StatBox label="Total" value={stats.totalArtifacts} color="#4af" />
      <StatBox label="NFTs" value={stats.totalNFTs} color="#ffd700" />
      <StatBox label="Videos" value={stats.videoCount} color="#ff8800" />
      <StatBox label="Storage" value={`${stats.storageUsedMB?.toFixed(1)}MB`} color="#aa44ff" />
    </div>
  );
}

function StatBox({ label, value, color }) {
  return (
    <div style={{ textAlign: 'center' }}>
      <div style={{ fontSize: 16, color, fontWeight: 'bold' }}>{value}</div>
      <div style={{ fontSize: 8, color: '#68a' }}>{label}</div>
    </div>
  );
}

// ─── FILTER BAR ───────────────────────────────────────────────────────────────
function FilterBar({ filters, setFilters }) {
  return (
    <div style={{
      display: 'flex',
      gap: 8,
      padding: '8px 12px',
      borderBottom: '1px solid #1a3a5c',
      flexWrap: 'wrap',
    }}>
      <FilterDropdown
        label="Type"
        value={filters.type}
        options={['all', 'video', 'audio', 'image', 'nft', 'gameAsset', 'simulation']}
        onChange={(v) => setFilters({ ...filters, type: v })}
      />
      <FilterDropdown
        label="Rarity"
        value={filters.rarity}
        options={['all', ...Object.keys(RARITY_COLORS)]}
        onChange={(v) => setFilters({ ...filters, rarity: v })}
      />
      <FilterDropdown
        label="Source"
        value={filters.source}
        options={['all', ...Object.keys(SOURCE_LABELS)]}
        onChange={(v) => setFilters({ ...filters, source: v })}
      />
      <input
        type="text"
        placeholder="Search..."
        value={filters.search}
        onChange={(e) => setFilters({ ...filters, search: e.target.value })}
        style={{
          flex: 1,
          minWidth: 100,
          padding: '4px 8px',
          background: '#0a1a2e',
          border: '1px solid #1a3a5c',
          borderRadius: 4,
          color: '#adf',
          fontSize: 9,
        }}
      />
    </div>
  );
}

function FilterDropdown({ label, value, options, onChange }) {
  return (
    <select
      value={value}
      onChange={(e) => onChange(e.target.value)}
      style={{
        padding: '4px 8px',
        background: '#0a1a2e',
        border: '1px solid #1a3a5c',
        borderRadius: 4,
        color: '#adf',
        fontSize: 9,
      }}
    >
      {options.map(opt => (
        <option key={opt} value={opt}>
          {label}: {opt === 'all' ? 'All' : opt}
        </option>
      ))}
    </select>
  );
}

// ─── UTILITIES ────────────────────────────────────────────────────────────────
function formatSize(bytes) {
  if (!bytes) return '0 B';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  return `${(bytes / 1024 / 1024 / 1024).toFixed(1)} GB`;
}

function formatAge(timestamp) {
  if (!timestamp) return 'Unknown';
  const age = Date.now() - timestamp;
  if (age < 60000) return 'Just now';
  if (age < 3600000) return `${Math.floor(age / 60000)}m ago`;
  if (age < 86400000) return `${Math.floor(age / 3600000)}h ago`;
  return `${Math.floor(age / 86400000)}d ago`;
}

function formatDate(timestamp) {
  if (!timestamp) return 'Unknown';
  return new Date(timestamp).toLocaleString();
}

// ─── STYLES ───────────────────────────────────────────────────────────────────
const styles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: '#070e1e',
    border: '1px solid #1a3a5c',
    borderRadius: 4,
    overflow: 'hidden',
  },
  header: {
    padding: '10px 12px',
    borderBottom: '1px solid #1a3a5c',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  title: {
    fontSize: 12,
    color: '#ffd700',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  content: {
    flex: 1,
    display: 'grid',
    gridTemplateColumns: '1fr 280px',
    overflow: 'hidden',
  },
  grid: {
    overflow: 'auto',
    padding: 12,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: 10,
    alignContent: 'start',
  },
  detail: {
    borderLeft: '1px solid #1a3a5c',
    overflow: 'auto',
  },
};

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────
export default function VaultDashboard({ vaultState = {} }) {
  const [selectedArtifact, setSelectedArtifact] = useState(null);
  const [filters, setFilters] = useState({
    type: 'all',
    rarity: 'all',
    source: 'all',
    search: '',
  });
  
  // Sample data if none provided
  const artifacts = vaultState.artifacts?.length > 0 ? vaultState.artifacts : [
    { id: 1, name: 'WorldModelVideo_001', type: 'video', rarity: 'epic', source: 'WorldModelSimulation', description: 'Full simulation of territorial defense scenario', contentSize: 52428800, createdAt: Date.now() - 3600000, viewCount: 12, downloadCount: 3 },
    { id: 2, name: 'NeuralRhythm_017', type: 'audio', rarity: 'rare', source: 'OrganismDream', description: 'Brain wave composition from alpha/theta states', contentSize: 8388608, createdAt: Date.now() - 7200000, viewCount: 45, downloadCount: 12 },
    { id: 3, name: 'DroneFormation_Diamond', type: 'gameAsset', rarity: 'legendary', source: 'SimulacrumPrediction', description: '3D model of optimal diamond formation', contentSize: 15728640, createdAt: Date.now() - 86400000, viewCount: 89, downloadCount: 34, nftData: { tokenId: 42, collectionId: 'NOVA_FORMATIONS', standard: 'ICRC-7', royaltyPercent: 5 } },
    { id: 4, name: 'PreplayVision_003', type: 'video', rarity: 'mythic', source: 'HippocampalPreplay', description: 'Future path prediction visualization', contentSize: 104857600, createdAt: Date.now() - 1800000, viewCount: 7, downloadCount: 1 },
    { id: 5, name: 'MemoryReplay_Patrol', type: 'simulation', rarity: 'uncommon', source: 'SharpWaveRipple', description: 'Replay of successful patrol mission', contentSize: 31457280, createdAt: Date.now() - 43200000, viewCount: 23, downloadCount: 8 },
  ];
  
  const stats = vaultState.stats || {
    totalArtifacts: artifacts.length,
    totalNFTs: artifacts.filter(a => a.nftData).length,
    videoCount: artifacts.filter(a => a.type === 'video').length,
    storageUsedMB: artifacts.reduce((s, a) => s + (a.contentSize || 0), 0) / 1024 / 1024,
  };
  
  // Apply filters
  const filteredArtifacts = useMemo(() => {
    return artifacts.filter(a => {
      if (filters.type !== 'all' && a.type !== filters.type) return false;
      if (filters.rarity !== 'all' && a.rarity !== filters.rarity) return false;
      if (filters.source !== 'all' && a.source !== filters.source) return false;
      if (filters.search && !a.name.toLowerCase().includes(filters.search.toLowerCase())) return false;
      return true;
    });
  }, [artifacts, filters]);
  
  return (
    <div style={styles.root}>
      <div style={styles.header}>
        <span style={styles.title}>💎 Artifact Vault</span>
        <span style={{ fontSize: 9, color: '#68a', marginLeft: 'auto' }}>
          {filteredArtifacts.length} artifacts
        </span>
      </div>
      
      <VaultStats stats={stats} />
      <FilterBar filters={filters} setFilters={setFilters} />
      
      <div style={styles.content}>
        <div style={styles.grid}>
          {filteredArtifacts.map(artifact => (
            <ArtifactCard
              key={artifact.id}
              artifact={artifact}
              selected={selectedArtifact?.id === artifact.id}
              onSelect={setSelectedArtifact}
            />
          ))}
          {filteredArtifacts.length === 0 && (
            <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: 40, color: '#446' }}>
              No artifacts match your filters
            </div>
          )}
        </div>
        
        <div style={styles.detail}>
          <ArtifactDetail artifact={selectedArtifact} />
        </div>
      </div>
    </div>
  );
}
