"""NOVA Solver — Constants"""
from enum import Enum
PHI = 1.6180339887498948482
PHI_INV = 0.6180339887498948482

class SolverState(str, Enum):
    IDLE = "IDLE"
    SOLVING = "SOLVING"
    CONVERGED = "CONVERGED"
    DIVERGED = "DIVERGED"
    TIMEOUT = "TIMEOUT"

class OptimMethod(str, Enum):
    PHI_GRADIENT = "PHI_GRADIENT"
    GOLDEN_SECTION = "GOLDEN_SECTION"
    NELDER_MEAD = "NELDER_MEAD"
    SIMULATED_ANNEALING = "SIMULATED_ANNEALING"
    BRUTE_FORCE = "BRUTE_FORCE"
