import { createQualityGate } from "./qualityGate.js";

const TEMPLATE_REGISTRY = [
  { id: "static-web", name: "Static Web App", entrypoint: "index.html", language: "html" },
  { id: "dashboard", name: "Dashboard App", entrypoint: "index.html", language: "html" },
  { id: "browser-extension", name: "Browser Extension", entrypoint: "manifest.json", language: "javascript" },
  { id: "node-service", name: "Node Service", entrypoint: "server.js", language: "javascript" },
  { id: "agent-tool", name: "Agent Tool", entrypoint: "src/index.js", language: "javascript" }
];

function slugify(value = "nova-app") {
  return String(value).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "nova-app";
}

function inferTemplate(prompt = "") {
  const text = prompt.toLowerCase();
  if (/extension|chrome|edge|browser/.test(text)) return "browser-extension";
  if (/api|service|server|backend/.test(text)) return "node-service";
  if (/dashboard|ops|analytics|control/.test(text)) return "dashboard";
  if (/agent|tool|mcp/.test(text)) return "agent-tool";
  return "static-web";
}

function createStaticFiles({ id, title, prompt }) {
  return [
    { path: "manifest.json", content: JSON.stringify({ schema: "nova-app-manifest-v0.1", id, title, type: "static-web", entrypoint: "index.html", prompt }, null, 2) + "\n" },
    { path: "README.md", content: `# ${title}\n\nGenerated by NOVA App Factory.\n\n## Purpose\n${prompt}\n\n## Run\nOpen index.html through the NOVA IDE preview lane.\n` },
    { path: "index.html", content: `<!doctype html>\n<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><link rel="stylesheet" href="styles.css"></head><body><main><h1>${title}</h1><p>${prompt}</p><section id="app"></section><button id="run">Run App</button></main><script src="app.js"></script></body></html>\n` },
    { path: "styles.css", content: "body{font-family:Inter,system-ui,sans-serif;background:#08111f;color:#eef5ff;margin:0}main{max-width:960px;margin:48px auto;padding:32px;border:1px solid #1f3a5f;border-radius:20px;background:#0d1b2e}button{padding:12px 18px;border-radius:12px;border:0;font-weight:700}\n" },
    { path: "app.js", content: `const state = { title: ${JSON.stringify(title)}, prompt: ${JSON.stringify(prompt)}, startedAt: new Date().toISOString() };\ndocument.getElementById("run").addEventListener("click", () => { document.getElementById("app").textContent = JSON.stringify(state, null, 2); });\n` },
    { path: "tests/app.test.js", content: "import assert from 'node:assert/strict';\nimport fs from 'node:fs';\nassert.ok(fs.existsSync(new URL('../index.html', import.meta.url)));\nassert.ok(fs.readFileSync(new URL('../manifest.json', import.meta.url),'utf8').includes('nova-app-manifest-v0.1'));\nconsole.log('app validation passed');\n" }
  ];
}

function createNodeServiceFiles({ id, title, prompt }) {
  return [
    { path: "manifest.json", content: JSON.stringify({ schema: "nova-app-manifest-v0.1", id, title, type: "node-service", entrypoint: "server.js", prompt }, null, 2) + "\n" },
    { path: "README.md", content: `# ${title}\n\nNOVA generated Node service.\n\n## Purpose\n${prompt}\n\n## Run\nnode server.js\n` },
    { path: "server.js", content: "import http from 'node:http';\nconst port = Number(process.env.PORT || 8787);\nconst server = http.createServer((req,res)=>{res.writeHead(200, {'content-type':'application/json'});res.end(JSON.stringify({ok:true, app:'" + id + "', path:req.url}, null, 2));});\nserver.listen(port, '127.0.0.1', ()=>console.log('service listening on '+port));\n" },
    { path: "tests/service.test.js", content: "import assert from 'node:assert/strict';\nimport fs from 'node:fs';\nassert.ok(fs.readFileSync(new URL('../server.js', import.meta.url),'utf8').includes('http.createServer'));\nconsole.log('service validation passed');\n" }
  ];
}

function createExtensionFiles({ id, title, prompt }) {
  return [
    { path: "manifest.json", content: JSON.stringify({ manifest_version: 3, name: title, version: "0.1.0", description: prompt.slice(0, 120), action: { default_popup: "popup.html" }, permissions: ["activeTab", "scripting", "storage"] }, null, 2) + "\n" },
    { path: "README.md", content: `# ${title}\n\nBrowser extension generated by NOVA App Factory.\n\nPurpose: ${prompt}\n` },
    { path: "popup.html", content: `<!doctype html><html><body><h1>${title}</h1><button id="capture">Capture Page</button><pre id="out"></pre><script src="popup.js"></script></body></html>\n` },
    { path: "popup.js", content: "document.getElementById('capture').onclick=async()=>{document.getElementById('out').textContent='Extension bridge ready. Execution requires operator approval.'};\n" },
    { path: "tests/extension.test.js", content: "import assert from 'node:assert/strict';\nimport fs from 'node:fs';\nconst manifest=JSON.parse(fs.readFileSync(new URL('../manifest.json', import.meta.url),'utf8'));\nassert.equal(manifest.manifest_version,3);\nconsole.log('extension validation passed');\n" }
  ];
}

export class AppFactory {
  constructor({ qualityGate = createQualityGate() } = {}) {
    this.qualityGate = qualityGate;
  }

  templates() {
    return TEMPLATE_REGISTRY.map((item) => ({ ...item }));
  }

  plan({ prompt = "", templateId } = {}) {
    const template = TEMPLATE_REGISTRY.find((item) => item.id === (templateId || inferTemplate(prompt))) || TEMPLATE_REGISTRY[0];
    const title = prompt.split(/[.\n]/)[0].trim().slice(0, 70) || template.name;
    const id = slugify(title);
    return { schema: "nova-app-plan-v0.1", id, title, template, prompt, createdAt: new Date().toISOString() };
  }

  generate(input = {}) {
    const plan = this.plan(input);
    let files;
    if (plan.template.id === "node-service") files = createNodeServiceFiles(plan);
    else if (plan.template.id === "browser-extension") files = createExtensionFiles(plan);
    else files = createStaticFiles(plan);
    const report = this.qualityGate.checkApp({ files, appId: plan.id });
    return { schema: "nova-generated-app-v0.1", plan, files, quality: report, createdAt: new Date().toISOString() };
  }
}

export function createAppFactory(options) {
  return new AppFactory(options);
}
