import { scanSecrets, evaluateAppCompleteness } from "./qualityGate.js";
import { sha256 } from "../storage.js";

const REQUIRED_DOC_SIGNALS = ["Run", "Generated by NOVA", "Purpose"];

export class CommercialReadinessGate {
  evaluate({ workspace = null, files = [], commandRuns = [], packagePlan = null } = {}) {
    const completeness = evaluateAppCompleteness(files);
    const secrets = scanSecrets(files);
    const docs = evaluateDocs(files);
    const tests = evaluateTests(commandRuns);
    const packaging = evaluatePackaging(packagePlan);
    const findings = [
      ...completeness.missing.map((item) => ({ severity: "blocker", code: `missing_${item}` })),
      ...secrets.map((item) => ({ severity: "blocker", code: "possible_secret", path: item.path })),
      ...docs.findings,
      ...tests.findings,
      ...packaging.findings
    ];
    const score = Math.max(0, Math.min(100, 100 - findings.reduce((sum, item) => sum + (item.severity === "blocker" ? 25 : item.severity === "warn" ? 10 : 3), 0)));
    return {
      schema: "nova-commercial-readiness-v0.1",
      ok: findings.filter((item) => item.severity === "blocker").length === 0,
      score,
      workspaceId: workspace?.id || null,
      checks: { completeness, docs, tests, packaging },
      findings,
      reportHash: sha256({ workspaceId: workspace?.id || null, score, findings }),
      createdAt: new Date().toISOString()
    };
  }
}

function evaluateDocs(files) {
  const readme = files.find((file) => file.path === "README.md");
  const findings = [];
  if (!readme) findings.push({ severity: "blocker", code: "missing_readme" });
  else for (const signal of REQUIRED_DOC_SIGNALS) if (!readme.content.includes(signal)) findings.push({ severity: "warn", code: "readme_missing_signal", signal });
  return { ok: findings.every((item) => item.severity !== "blocker"), findings };
}

function evaluateTests(commandRuns) {
  const runs = commandRuns || [];
  const passed = runs.filter((run) => run.ok).length;
  const findings = passed ? [] : [{ severity: "blocker", code: "no_passing_command_run" }];
  return { ok: passed > 0, passed, total: runs.length, findings };
}

function evaluatePackaging(packagePlan) {
  if (!packagePlan) return { ok: false, findings: [{ severity: "warn", code: "package_plan_not_generated" }] };
  if (!packagePlan.ok) return { ok: false, findings: [{ severity: "blocker", code: "package_plan_failed" }] };
  if (!packagePlan.manifest?.manifestHash) return { ok: false, findings: [{ severity: "blocker", code: "package_manifest_missing_hash" }] };
  return { ok: true, lane: packagePlan.lane, findings: [] };
}

export function createCommercialReadinessGate() {
  return new CommercialReadinessGate();
}
