import { appendRecord, readRecords, sha256 } from "../storage.js";
import { FileSystemVault, safeId } from "./fileVault.js";

const DEFAULT_WORKSPACE_LIMIT = 100;

export class WorkspaceManager {
  constructor({ vault = new FileSystemVault() } = {}) {
    this.vault = vault;
    this.workspaces = new Map();
  }

  async hydrate() {
    const records = await readRecords("ide_workspaces", { limit: DEFAULT_WORKSPACE_LIMIT });
    for (const record of records) {
      if (record.payload?.workspace?.id) this.workspaces.set(record.payload.workspace.id, record.payload.workspace);
    }
    return this;
  }

  async createWorkspace({ name = "NOVA Workspace", template = "web", source = "operator", files = [], metadata = {} } = {}) {
    const id = `${safeId(name, "workspace")}-${Date.now().toString(36)}`;
    const workspace = {
      schema: "nova-ide-workspace-v0.1",
      id,
      name: String(name || "NOVA Workspace").slice(0, 120),
      template: safeId(template, "web"),
      source: String(source || "operator").slice(0, 60),
      entry: entryForTemplate(template),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      metadata
    };
    this.vault.ensureWorkspace(id);
    if (files.length) this.vault.writeMany(id, files);
    else this.vault.writeMany(id, defaultTemplateFiles(workspace));
    workspace.manifest = this.vault.manifest(id);
    workspace.workspaceHash = sha256(workspace);
    this.workspaces.set(id, workspace);
    await appendRecord("ide_workspaces", { type: "workspace_created", workspace });
    return workspace;
  }

  listWorkspaces() {
    return [...this.workspaces.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  }

  getWorkspace(id) {
    const workspace = this.workspaces.get(id);
    if (!workspace) throw new Error("workspace_not_found");
    return workspace;
  }

  async touchWorkspace(id, patch = {}) {
    const workspace = this.getWorkspace(id);
    const next = { ...workspace, ...patch, updatedAt: new Date().toISOString() };
    next.manifest = this.vault.manifest(id);
    next.workspaceHash = sha256(next);
    this.workspaces.set(id, next);
    await appendRecord("ide_workspaces", { type: "workspace_updated", workspace: next });
    return next;
  }

  async writeFile(id, file, content) {
    this.getWorkspace(id);
    const meta = this.vault.writeFile(id, file, content);
    await this.touchWorkspace(id);
    await appendRecord("ide_files", { type: "file_written", workspaceId: id, file: meta });
    return meta;
  }

  readFile(id, file) {
    this.getWorkspace(id);
    return this.vault.readFile(id, file);
  }

  listFiles(id) {
    this.getWorkspace(id);
    return this.vault.listFiles(id);
  }

  manifest(id) {
    this.getWorkspace(id);
    return this.vault.manifest(id);
  }
}

export function entryForTemplate(template = "web") {
  const key = String(template).toLowerCase();
  if (key === "python") return "main.py";
  if (key === "node") return "src/server.js";
  if (key === "extension") return "manifest.json";
  return "index.html";
}

export function defaultTemplateFiles(workspace) {
  if (workspace.template === "python") {
    return [
      { path: "main.py", content: "def main():\n    print('NOVA workspace ready')\n\nif __name__ == '__main__':\n    main()\n" },
      { path: "README.md", content: `# ${workspace.name}\n\nPython workspace generated by NOVA IDE.\n` }
    ];
  }
  return [
    { path: "index.html", content: `<!doctype html>\n<html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>${workspace.name}</title><link rel=\"stylesheet\" href=\"styles.css\"></head><body><main><h1>${workspace.name}</h1><p>NOVA workspace ready.</p><button id=\"action\">Run</button></main><script src=\"app.js\"></script></body></html>\n` },
    { path: "styles.css", content: "body{font-family:Inter,system-ui,sans-serif;background:#08111f;color:#e8f3ff;margin:0}main{max-width:900px;margin:auto;padding:48px}button{padding:12px 18px;border:0;border-radius:8px;background:#66bbff;color:#06101c;font-weight:700}\n" },
    { path: "app.js", content: "document.getElementById('action')?.addEventListener('click',()=>alert('NOVA app is alive'));\n" },
    { path: "README.md", content: `# ${workspace.name}\n\nWeb workspace generated by NOVA IDE.\n` }
  ];
}
