// ─── NOVA / PARALLAX — AntifragilityEngine ───────────────────────────────────
// Paper II+III: Antifragility as sovereign immune system and stress response.
// "That which does not kill the organism makes it stronger" — Taleb, NOVA edition.
//
// The AntifragilityEngine is the immune system of the FusionOrganism.
// Every output generated by any paper engine passes through this module
// before being returned to a caller. Outputs that survive stress tests
// are φ-boosted; outputs that break are quarantined and logged.
//
// Architecture:
//   STRESS_TEST    — inject controlled perturbation, measure response
//   FRAGILITY_SCORE— score any computation result on fragility spectrum
//   RESILIENCE_BOOST — apply φ-weighted resilience multiplier on survivors
//   IMMUNE_MEMORY  — rolling 64-entry log of stressors + outcomes
//   ANTIFRAGILE_GAIN — measure how much the system GAINED from stress
//
// φ-axis: fragility → robustness → antifragility
//   score < 0     → FRAGILE   (hurts from randomness)
//   score = 0     → ROBUST    (no effect from randomness)
//   score > 0     → ANTIFRAGILE (gains from randomness)
//
// Medina Tech | Alfredo Medina Hernandez | Dallas, TX | 2026
// COPYRIGHT © 2024-2026 ALFREDO MEDINA HERNANDEZ. ALL RIGHTS RESERVED.

import { clamp, PHI, PHI_INV } from './core';

// ── Types ─────────────────────────────────────────────────────────────────────

export type FragilityClass = 'FRAGILE' | 'ROBUST' | 'ANTIFRAGILE';

export interface StressResult {
  originalValue:    number;
  stressedValue:    number;
  delta:            number;       // stressedValue − originalValue
  fragility:        number;       // < 0 fragile, 0 robust, > 0 antifragile
  fragClass:        FragilityClass;
  resilience:       number;       // [0,1] — how well it absorbed
  antifragileGain:  number;       // net gain beyond survival (φ-boosted)
  stressorApplied:  string;
  timestamp:        number;
}

export interface ImmuneRecord {
  stressor:    string;
  fragility:   number;
  survived:    boolean;
  gain:        number;
  timestamp:   number;
}

// ── Constants ─────────────────────────────────────────────────────────────────

const STRESS_MAGNITUDE = 0.3;         // 30% perturbation — Taleb's "barbell"
const QUARANTINE_THRESHOLD = -0.5;    // below this → quarantine (too fragile)
const ANTIFRAGILE_GAIN_COEFF = PHI;   // φ bonus on antifragile survivors
const IMMUNE_MEMORY_CAP = 64;

// ── Internal state ─────────────────────────────────────────────────────────

const immuneMemory: ImmuneRecord[] = [];
let totalStressTests = 0;
let antifragileCount = 0;
let fragileCount     = 0;
let robustCount      = 0;

// ── Stressor catalogue ────────────────────────────────────────────────────────
// Each stressor applies a different perturbation to the raw value.

type Stressor = (v: number) => number;

const STRESSORS: Record<string, Stressor> = {
  GAUSSIAN_NOISE:   v => v + (Math.random() - 0.5) * 2 * STRESS_MAGNITUDE * v,
  SPIKE_UP:         v => v * (1 + PHI * STRESS_MAGNITUDE),
  SPIKE_DOWN:       v => v * (1 - STRESS_MAGNITUDE),
  LATENCY_DELAY:    v => v * PHI_INV,              // simulates timeout pressure
  ENTROPY_INJECTION:v => v + Math.random() * 0.1 * v,
  LOAD_DOUBLING:    v => v * 2.0,                  // double load stress test
  SUBSTRATE_CUT:    v => v * (1 - PHI_INV),        // lose 38.2% of bandwidth
};

const STRESSOR_NAMES = Object.keys(STRESSORS);

function randomStressor(): [string, Stressor] {
  const name = STRESSOR_NAMES[Math.floor(Math.random() * STRESSOR_NAMES.length)];
  return [name, STRESSORS[name]];
}

// ── Core: stress-test a scalar value ─────────────────────────────────────────

export function stressTest(value: number, stressorName?: string): StressResult {
  totalStressTests++;

  const [sName, stressor] = stressorName && STRESSORS[stressorName]
    ? [stressorName, STRESSORS[stressorName]]
    : randomStressor();

  const stressed = stressor(value);
  const delta    = stressed - value;

  // Fragility = how the derivative of harm scales with the magnitude of disorder
  // Positive delta after stress → antifragile (gained); negative → fragile (hurt)
  const fragility = clamp(delta / (Math.abs(value) + 1e-10), -1, 1);

  let fragClass: FragilityClass;
  if      (fragility >  0.05) fragClass = 'ANTIFRAGILE';
  else if (fragility < -0.05) fragClass = 'FRAGILE';
  else                         fragClass = 'ROBUST';

  const survived       = fragility >= QUARANTINE_THRESHOLD;
  const resilience     = clamp(1 - Math.abs(fragility), 0, 1);
  const antifragileGain = fragClass === 'ANTIFRAGILE'
    ? clamp(fragility * ANTIFRAGILE_GAIN_COEFF, 0, PHI)
    : 0;

  // Update counters
  if (fragClass === 'ANTIFRAGILE') antifragileCount++;
  else if (fragClass === 'FRAGILE') fragileCount++;
  else robustCount++;

  // Write immune memory (rolling)
  if (immuneMemory.length >= IMMUNE_MEMORY_CAP) immuneMemory.shift();
  immuneMemory.push({ stressor: sName, fragility, survived, gain: antifragileGain, timestamp: Date.now() });

  return {
    originalValue: value,
    stressedValue: stressed,
    delta,
    fragility,
    fragClass,
    resilience,
    antifragileGain,
    stressorApplied: sName,
    timestamp: Date.now(),
  };
}

// ── Score an arbitrary object's numeric fields ────────────────────────────────
// Returns a composite antifragility score for any result object.

export function scoreResult(result: Record<string, unknown>): {
  compositeFragility: number;
  fragClass: FragilityClass;
  fieldsScored: number;
  recommendation: string;
} {
  const numerics: number[] = [];
  for (const v of Object.values(result)) {
    if (typeof v === 'number' && isFinite(v)) numerics.push(v);
  }
  if (!numerics.length) {
    return { compositeFragility: 0, fragClass: 'ROBUST', fieldsScored: 0, recommendation: 'NO_NUMERIC_FIELDS' };
  }

  let fragSum = 0;
  for (const n of numerics) {
    const sr = stressTest(n);
    fragSum += sr.fragility;
  }
  const composite = clamp(fragSum / numerics.length, -1, 1);

  let fragClass: FragilityClass;
  if      (composite >  0.05) fragClass = 'ANTIFRAGILE';
  else if (composite < -0.05) fragClass = 'FRAGILE';
  else                         fragClass = 'ROBUST';

  const recommendation = fragClass === 'FRAGILE'
    ? 'ADD_REDUNDANCY — apply barbell strategy'
    : fragClass === 'ANTIFRAGILE'
    ? 'AMPLIFY — system gains from disorder, increase exposure'
    : 'HOLD — system is robust, maintain current load';

  return { compositeFragility: composite, fragClass, fieldsScored: numerics.length, recommendation };
}

// ── Apply φ-resilience boost to a survivor output ────────────────────────────
// After a value survives stress, boost it by its antifragile gain.

export function applyResilienceBoost(value: number, stressResult: StressResult): number {
  if (!isFinite(value)) return value;
  return value + stressResult.antifragileGain * PHI_INV;
}

// ── Barbell strategy: combine conservative core + speculative tail ────────────
// Classic Taleb barbell: 90% safe + 10% high-variance.

export function barbell(conservativeValue: number, speculativeValue: number, safetyRatio = 0.9): number {
  const sr = clamp(safetyRatio, 0, 1);
  return sr * conservativeValue + (1 - sr) * speculativeValue;
}

// ── Immune system status ──────────────────────────────────────────────────────

export function getImmuneStatus(): {
  totalStressTests:  number;
  antifragileCount:  number;
  robustCount:       number;
  fragileCount:      number;
  antifragileRatio:  number;
  recentMemory:      ImmuneRecord[];
  healthVerdict:     string;
} {
  const total = totalStressTests || 1;
  const antifragileRatio = antifragileCount / total;

  const healthVerdict = antifragileRatio > 0.5
    ? 'ANTIFRAGILE — organism gains from disorder'
    : antifragileRatio > 0.2
    ? 'ROBUST — organism absorbs disorder'
    : 'FRAGILE — organism needs barbell hardening';

  return {
    totalStressTests,
    antifragileCount,
    robustCount,
    fragileCount,
    antifragileRatio: clamp(antifragileRatio, 0, 1),
    recentMemory: immuneMemory.slice(-10),
    healthVerdict,
  };
}

// ── Reset (for test/terrace bench) ───────────────────────────────────────────

export function resetImmuneMemory(): void {
  immuneMemory.length = 0;
  totalStressTests = 0;
  antifragileCount = 0;
  fragileCount = 0;
  robustCount = 0;
}
